{
 "title": "Docker Metric",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Docker Container CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "com.docker.swarm.service.name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "usage" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nas.home.juari.net" }
     ]
    }
   ]
  },
  {
   "title": "Usage Limit",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "com.docker.swarm.service.name" ], "type": "tag" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "limit" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Limit" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nas.home.juari.net" }
     ]
    }
   ]
  },
  {
   "title": "Docker Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "com.docker.swarm.service.name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "usage" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nas.home.juari.net" }
     ]
    }
   ]
  },
  {
   "title": "Running Service",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "service_name" ], "type": "tag" }
     ],
     "measurement": "docker_swarm",
     "select": [
      [
       { "params": [ "tasks_running" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Replica" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nas.home.juari.net" }
     ]
    }
   ]
  },
  {
   "title": "Docker Container Network Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "com.docker.swarm.service.name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "receive" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nas.home.juari.net" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "com.docker.swarm.service.name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "nas.home.juari.net" }
     ]
    }
   ]
  }
 ]
}